version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
  clone-child-repo:
    docker:
      - image: cimg/android:2024.01
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:V/PxmiAO+zs9Y00a9Wjd5Q1DDRtHInFhBl3bgLDXVfk"
      - run:
          name: Add GitHub to known_hosts
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Initialize Git Submodules
          command: |
            git submodule sync
            git submodule update --init --recursive
      

  build-and-test:
    docker:
      - image: cimg/android:2024.01
    steps:
      - checkout
      - clone-child-repo
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Run Tests
          command: |
            ./gradlew testDebugUnitTest
      - android/save-gradle-cache
      - android/save-build-cache
      - run:
          name: Build Debug APK
          command: ./gradlew assembleRelease
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/reports
          destination: reports

  build-release:
    docker:
      - image: cimg/android:2024.01
    steps:
      - checkout
      - clone-child-repo
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Build Release APK
          command: ./gradlew assembleRelease
      - android/save-gradle-cache
      - android/save-build-cache
      - store_artifacts:
          path: app/build/outputs/apk/release
          destination: release-apk

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - main
                - develop
      - build-release:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - main